[package]
name = "gender_guesser"
version = "0.1.0"
edition = "2021"
authors = ["Radu"]
description = "A library that guesses the gender of a given name."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
